// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: ltv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LTVRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CustomerId      string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	RecentSpend     float64                `protobuf:"fixed64,2,opt,name=recent_spend,json=recentSpend,proto3" json:"recent_spend,omitempty"`
	EngagementScore float64                `protobuf:"fixed64,3,opt,name=engagement_score,json=engagementScore,proto3" json:"engagement_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LTVRequest) Reset() {
	*x = LTVRequest{}
	mi := &file_ltv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LTVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTVRequest) ProtoMessage() {}

func (x *LTVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ltv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTVRequest.ProtoReflect.Descriptor instead.
func (*LTVRequest) Descriptor() ([]byte, []int) {
	return file_ltv_proto_rawDescGZIP(), []int{0}
}

func (x *LTVRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *LTVRequest) GetRecentSpend() float64 {
	if x != nil {
		return x.RecentSpend
	}
	return 0
}

func (x *LTVRequest) GetEngagementScore() float64 {
	if x != nil {
		return x.EngagementScore
	}
	return 0
}

type LTVResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PredictedLtv    float64                `protobuf:"fixed64,1,opt,name=predicted_ltv,json=predictedLtv,proto3" json:"predicted_ltv,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Explanation     string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LTVResponse) Reset() {
	*x = LTVResponse{}
	mi := &file_ltv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LTVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTVResponse) ProtoMessage() {}

func (x *LTVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ltv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTVResponse.ProtoReflect.Descriptor instead.
func (*LTVResponse) Descriptor() ([]byte, []int) {
	return file_ltv_proto_rawDescGZIP(), []int{1}
}

func (x *LTVResponse) GetPredictedLtv() float64 {
	if x != nil {
		return x.PredictedLtv
	}
	return 0
}

func (x *LTVResponse) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *LTVResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_ltv_proto protoreflect.FileDescriptor

const file_ltv_proto_rawDesc = "" +
	"\n" +
	"\tltv.proto\x12\x03ltv\"{\n" +
	"\n" +
	"LTVRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\frecent_spend\x18\x02 \x01(\x01R\vrecentSpend\x12)\n" +
	"\x10engagement_score\x18\x03 \x01(\x01R\x0fengagementScore\"\x7f\n" +
	"\vLTVResponse\x12#\n" +
	"\rpredicted_ltv\x18\x01 \x01(\x01R\fpredictedLtv\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x01R\x0fconfidenceScore\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation2=\n" +
	"\n" +
	"LTVService\x12/\n" +
	"\n" +
	"PredictLTV\x12\x0f.ltv.LTVRequest\x1a\x10.ltv.LTVResponseB\rZ\vKIKI/api/pbb\x06proto3"

var (
	file_ltv_proto_rawDescOnce sync.Once
	file_ltv_proto_rawDescData []byte
)

func file_ltv_proto_rawDescGZIP() []byte {
	file_ltv_proto_rawDescOnce.Do(func() {
		file_ltv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ltv_proto_rawDesc), len(file_ltv_proto_rawDesc)))
	})
	return file_ltv_proto_rawDescData
}

var file_ltv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ltv_proto_goTypes = []any{
	(*LTVRequest)(nil),  // 0: ltv.LTVRequest
	(*LTVResponse)(nil), // 1: ltv.LTVResponse
}
var file_ltv_proto_depIdxs = []int32{
	0, // 0: ltv.LTVService.PredictLTV:input_type -> ltv.LTVRequest
	1, // 1: ltv.LTVService.PredictLTV:output_type -> ltv.LTVResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ltv_proto_init() }
func file_ltv_proto_init() {
	if File_ltv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ltv_proto_rawDesc), len(file_ltv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ltv_proto_goTypes,
		DependencyIndexes: file_ltv_proto_depIdxs,
		MessageInfos:      file_ltv_proto_msgTypes,
	}.Build()
	File_ltv_proto = out.File
	file_ltv_proto_goTypes = nil
	file_ltv_proto_depIdxs = nil
}
